name: CI & Release

permissions:
  contents: write

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  GO_VERSION: "1.24.x"
  TAR_OPTIONS: --skip-old-files

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run generate-go build-ui
        run: make generate-go build-ui

      - name: Run tests
        run: make test

      - name: Build platforms
        run: make build-server

      - name: Prepare release artifacts
        run: |
          mkdir -p release
          cp bin/* release/
          cd release
          sha256sum * > checksums.txt

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jucosuma-${{ env.VERSION }}
          path: release/*

  release:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Download artifacts from build
        uses: actions/download-artifact@v4
        with:
          name: jucosuma-${{ env.VERSION }}
          path: release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          target_commitish: ${{ github.sha }}
          name: v${{ env.VERSION }}
          body: |
            Automated release for version v${{ env.VERSION }}.
            Includes:
            - All compiled binaries
            - SHA256 checksums
          files: |
            release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
