name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

permissions:
  contents: write  # nötig, damit der Release-Job Releases anlegen darf

env:
  GO_VERSION: "1.24.x"
  TAR_OPTIONS: --skip-old-files

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate & build UI
        run: make generate-go build-ui

      - name: Run tests
        run: make test

      - name: Build platforms
        run: make build-server

      - name: Smoke check (linux amd64)
        run: ./bin/jucosuma-v${{ env.VERSION }}-linux-amd64 --version

      - name: Package release artifacts (zip + checksums)
        run: |
          mkdir -p release
          zip -j "release/jucosuma-v${{ env.VERSION }}-binaries.zip" ./bin/*
          (cd release && sha256sum * > SHA256SUMS.txt)

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jucosuma-${{ env.VERSION }}
          path: release/*

  release:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Download artifacts from build
        uses: actions/download-artifact@v4
        with:
          name: jucosuma-${{ env.VERSION }}
          path: release

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: v${{ env.VERSION }}
          body: |
            Automated release for version v${{ env.VERSION }}.
            Includes zipped multiplatform binaries and checksums.
          draft: false
          prerelease: false

      - name: Upload ZIP asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/jucosuma-v${{ env.VERSION }}-binaries.zip
          asset_name: jucosuma-v${{ env.VERSION }}-binaries.zip
          asset_content_type: application/zip

      - name: Upload checksums
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/SHA256SUMS.txt
          asset_name: SHA256SUMS.txt
          asset_content_type: text/plain
